# Generated by Django 4.2.3 on 2023-08-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=260),
        ),
    ]
